[package]
name = "sr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
pyo3 = { version = "0.27.2", features = ["auto-initialize"] }
anyhow = "1.0.100"
indicatif = "0.18.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
